apiVersion: v1
kind: Service
metadata:
  name: paysecure-svc
  namespace: paysecure
spec:
  type: LoadBalancer
  selector:
    app: paysecure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
