apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paysecure-app
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - paysecure
  selector:
    matchLabels:
      app: paysecure-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
